prog :main.o enemy.o
	gcc -o prog main.o enemy.o -lSDL -lSDL_image  -lSDL_mixer 
main.o :main.c
	gcc -o main.o -c  main.c  -lSDL -lSDL_image  -lSDL_mixer 
enemy.o :enemy.c
	gcc -o enemy.o -c enemy.c -lSDL -lSDL_image  -lSDL_mixer 



