prog: main.o background_partage.o
	gcc main.o background_partage.o -o prog -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -lm
main.o:main.c 
	gcc -c main.c 
background_partage.o:background_partage.c 
	gcc -c background_partage.c 
